### ISSUE TITLE
Publish under both CJS and ESM

### ISSUE THREAD

**Issue by kaspar-p** [syntax-tree/unist-util-find#11]
For projects that use CJS, it's not possible to use this library. This is a huge usage blocker for some projects.

**Comment by blahah** [comment]
Fixed in #5 by @crutchcorn (💜 thanks).

Included in release [`v1.0.3`](https://github.com/blahah/unist-util-find/releases/tag/v1.0.3)

**Comment by crutchcorn** [comment]
Just as a heads up @blahah I think this issue is requesting the opposite of what my PR did 😅

Currently, as I recall, we publish ESM only, as does the Unified ecosystem.

**Comment by kaspar-p** [comment]
Hm. Grumble grumble. I understand that ESM is handy and the way of the future, but there are ways to develop in ESM, and publish in both. I hoped that this could have been the resolution.

**Comment by blahah** [comment]
Ah, how silly of me. I parsed the issue wrongly. Sorry @kaspar-p (and thank you @crutchcorn for pointing it out).

Hmm, I also did *not* do a major version bump as I should have when publishing the ESM change.

As to the first problem - @kaspar-p , can you not just depend on the previous CJS version (`v1.0.2`)? There are no functional changes in the ESM update (and there won't be in the future - this is a very long-term stable module).

As to the second - @crutchcorn, thoughts about whether to unpublish and do a major bump? Unfortunately the module is widely used so it might already have caused a problem for some.

**Comment by crutchcorn** [comment]
I would see if you're able to unpublish and republish under a 2.0. However, I suspect NPM might disallow it 😅

**Comment by blahah** [comment]
Ah it was too late - others have already published updates depending on the new version! Lesson learned for future: don't publish when sleep deprived.

**Comment by dburles** [comment]
I just read this thread after posting #12. Like I mentioned there, the solution is to publish 1.0.2 (the last CJS version) as version 1.0.4, and then just publish the ESM version as 2.0.0.

**Comment by wooorm** [comment]
Solved, everything’s ESM-only now, no plans to add dual.
