### ISSUE TITLE
1.0.3 should have been major version 2.0.0

### ISSUE THREAD

**Issue by dburles** [syntax-tree/unist-util-find#12]
Migrating to ESM is a breaking change! A CJS dependency of this package (https://github.com/mrzmmr/unist-util-find-all-between) is making a require call to this package and has broken our tests in CI with an `ERR_REQUIRE_ESM` error.

Solution: Publish 1.0.2 as 1.0.4 and publish this version as 2.0.0.

Related https://github.com/mrzmmr/unist-util-find-all-between/issues/25

**Comment by talatkuyuk** [comment]
A package can support both CommonJS and ESM. You don't need to create two versions. https://www.typescriptlang.org/docs/handbook/esm-node.html

**Comment by blahah** [comment]
Agree with the solution, thanks. Will do the publish in the next couple of hours

**Comment by wooorm** [comment]
Dual can be complex to get right, it’s more involved, and I don’t think it’s very useful in this case: all unified projects are ESM only.

So I’d recommend patching with a CJS release, and releasing ESM as a v2!

**Comment by wooorm** [comment]
Also, if you’re no longer interested in maintaining this, we at unified can do that. Move it over. Streamline it with the rest of unified!

**Comment by danilmoro3** [comment]
When the 1.0.4 version is expected ?

**Comment by alvinometric** [comment]
@wooorm There isn't a `uinst-util-find-index`, so maybe Unified can make that as a replacement until this repo is transferred over?

**Comment by blahah** [comment]
Happy to make the transfer - I don't want to gatekeep an important part of a large ecosystem.

@wooorm do I just transfer the repo? How do we handle the npm package?

**Comment by wooorm** [comment]
Add me on npm, and transfer the repo to me personally, I'll move it to the orgs later, can fix things tomorrow!

**Comment by wooorm** [comment]
This was solved btw, thanks y’all, and @blahah in particular! :)
