### ISSUE TITLE
publish 1.0.2 from current master?

### ISSUE THREAD

**Issue by Trott** [syntax-tree/unist-util-find#3]
Can we get a 1.0.2 release? It looks like a minor issue (removal/update of a sub-dependency that has a CVE against it) is solved by that. 1.0.1 is not vulnerable, but having the updated dependencies in production will make auditing easier.

**Comment by blahah** [comment]
Done:

https://github.com/blahah/unist-util-find/releases/tag/v1.0.2

https://www.npmjs.com/package/unist-util-find/v/1.0.2
